pub mod forgemd;
pub mod session;
pub mod embedding;
pub mod vec_store;
pub mod fts_store;
pub mod hybrid;
pub mod compaction;
pub mod indexer;
pub mod combined;
pub mod memory_db;

pub use forge_core::{EmbeddingProvider, MemoryChunk, MemoryRetriever, RetrieveOptions};
pub use forgemd::ForgemdRetriever;
pub use session::SessionManager;
pub use embedding::{OpenAIEmbedding, GeminiEmbedding};
pub use vec_store::SqliteVecStore;
pub use fts_store::Fts5Store;
pub use hybrid::HybridRetriever;
pub use compaction::LlmCompaction;
pub use indexer::IncrementalIndexer;
pub use combined::CombinedRetriever;
pub use memory_db::{MemoryDb, content_hash};
